/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectstudentregistration;

import forms.TableAllStudant;
import javax.swing.JOptionPane;

/**
 *
 * @author marce
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    private void showDataInTable() {
//        StudantData data = getData(registration);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtEnrollmet = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnInclude = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSearchName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sistema de Registro de Alunos");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 660, 60));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Identificação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEnrollmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnrollmetActionPerformed(evt);
            }
        });
        jPanel1.add(txtEnrollmet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, 25));
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 80, 25));

        jLabel2.setText("Matrícula");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel5.setText("Idade");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 280, 25));

        jLabel3.setText("Nome");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 260, 25));

        jLabel4.setText("E-mail");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 470, 150));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInclude.setText("Incluir");
        btnInclude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncludeActionPerformed(evt);
            }
        });
        jPanel2.add(btnInclude, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 80, 25));

        btnChange.setText("Alterar");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });
        jPanel2.add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 80, 25));

        btnDelete.setText("Excluir");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 80, 25));

        btnClear.setText("Limpar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 80, 25));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 470, 80));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 20, 490));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 80, 25));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel3.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 80, 25));

        jLabel1.setText("Matrícula");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));
        jPanel3.add(txtSearchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 200, 25));

        jLabel8.setText("Nome");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 470, 100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        chengeDataStudant();
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        deleteDataStudant();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnIncludeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncludeActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_btnIncludeActionPerformed

    private void txtEnrollmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnrollmetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnrollmetActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here

        if (!txtSearch.getText().isEmpty() && txtSearchName.getText().isEmpty()) {
            searchRegistration();
        } else if (txtSearch.getText().isEmpty() && !txtSearchName.getText().isEmpty()) {
            serachForName();
        } else if (!txtSearch.getText().isEmpty() && !txtSearchName.getText().isEmpty()) {
            searchRegistration();
        }else{
            reportAllStudant();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearData();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInclude;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEnrollmet;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearchName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void clearData() {
        txtEnrollmet.setText("");
        txtUserName.setText("");
        txtEmail.setText("");
        txtAge.setText("");
        txtSearch.setText("");
        txtSearchName.setText("");
    }

    private void searchRegistration() {
        try {
            int registrationNumber = Integer.parseInt(txtSearch.getText());
            StudantData std = CrudStudant.getInstance().getData(registrationNumber);
            if (std == null) {
                JOptionPane.showMessageDialog(this, "Matrícula não encontrada!");
            } else {
                txtEnrollmet.setText(Integer.toString(std.getRegistration()));
                txtUserName.setText(std.getName());
                txtEmail.setText(std.getEmail());
                txtAge.setText(Integer.toString(std.getAge()));
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Dados da Matrícula Incorreto!\nInforme somete números!", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void serachForName() {
        String searchName = txtSearchName.getText();
        StudantData std = CrudStudant.getInstance().getDataForName(searchName);
        if (std == null) {
            JOptionPane.showMessageDialog(this, "Registro não encontrado!");
        } else {
            txtEnrollmet.setText(Integer.toString(std.getRegistration()));
            txtUserName.setText(std.getName());
            txtEmail.setText(std.getEmail());
            txtAge.setText(Integer.toString(std.getAge()));
        }
    }

    private void chengeDataStudant() {
        try {
            StudantData std = new StudantData();
            std.setRegistration(Integer.parseInt(txtEnrollmet.getText()));
            std.setName(txtUserName.getText());
            std.setEmail(txtEmail.getText());
            std.setAge(Integer.parseInt(txtAge.getText()));

            int sucessefull = CrudStudant.getInstance().editData(std);

            if (sucessefull == 0) {
//            JOptionPane.showConfirmDialog(null, "Atualizado com Sucesso!");
                clearData();
            }
         } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Dados da Matrícula e Idade Incorreto!\nInforme somete números!", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void save() {
        try {
            StudantData std = new StudantData();
            std.setRegistration(Integer.parseInt(txtEnrollmet.getText()));
            std.setName(txtUserName.getText());
            std.setEmail(txtEmail.getText());
            std.setAge(Integer.parseInt(txtAge.getText()));

            int status = CrudStudant.getInstance().create(std);

            if (status == 0) {
                clearData();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Dados da Matrícula e Idade Incorreto!\nInforme somete números!", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void deleteDataStudant() {
        try {
            int registrationStudant = Integer.parseInt(txtEnrollmet.getText());
            int status = CrudStudant.getInstance().deleteDataStudantBank(registrationStudant);
            if (status == 0) {
                clearData();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Dados da Matrícula Incorreto!\nInforme somete números!", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void reportAllStudant() {
        TableAllStudant studantTable = new TableAllStudant();
        studantTable.setVisible(true);
    }
}
